---
abstract: 'Parser and Object Model for wxFormBuilder Project Files (.fpb files)'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.80
  Test::More: 0.47
  Test::NoWarnings: 0.084
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: FBP
name: FBP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  IO::File: 1.14
  Mouse: 0.61
  Params::Util: 1.00
  XML::SAX: 0.96
  perl: 5.8.5
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/FBP
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/FBP
version: 0.26
